local C = {}
-- game config
C.GAME_TITLE = "Welcome To Raccon City"
C.SCREEN_WIDTH = 1280
C.SCREEN_HEIGHT = 720
C.FPS_CAP = 60

C.TILE_SIZE = 16
C.TILE_SPACING = 1
C.MAP_COLUMNS = 27
C.MAP_ROWS = 18

C.PLAYER_SPEED_ZOMBIE = 150
C.PLAYER_SPEED_HUMAN = 200

C.INITIAL_ZOMBIES = 4
C.INITIAL_HUMANS = 16
C.GAME_TIME_LIMIT = 120

return C
